/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardWillRouteImport } from './routes/dashboard.will'
import { Route as DashboardVaultRouteImport } from './routes/dashboard.vault'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardNomineesRouteImport } from './routes/dashboard.nominees'
import { Route as DashboardLifelineRouteImport } from './routes/dashboard.lifeline'
import { Route as DashboardLegacyRouteImport } from './routes/dashboard.legacy'
import { Route as DashboardContactsRouteImport } from './routes/dashboard.contacts'
import { Route as DashboardActivityRouteImport } from './routes/dashboard.activity'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWillRoute = DashboardWillRouteImport.update({
  id: '/will',
  path: '/will',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVaultRoute = DashboardVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNomineesRoute = DashboardNomineesRouteImport.update({
  id: '/nominees',
  path: '/nominees',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLifelineRoute = DashboardLifelineRouteImport.update({
  id: '/lifeline',
  path: '/lifeline',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLegacyRoute = DashboardLegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContactsRoute = DashboardContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivityRoute = DashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/legacy': typeof DashboardLegacyRoute
  '/dashboard/lifeline': typeof DashboardLifelineRoute
  '/dashboard/nominees': typeof DashboardNomineesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/vault': typeof DashboardVaultRoute
  '/dashboard/will': typeof DashboardWillRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/legacy': typeof DashboardLegacyRoute
  '/dashboard/lifeline': typeof DashboardLifelineRoute
  '/dashboard/nominees': typeof DashboardNomineesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/vault': typeof DashboardVaultRoute
  '/dashboard/will': typeof DashboardWillRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/legacy': typeof DashboardLegacyRoute
  '/dashboard/lifeline': typeof DashboardLifelineRoute
  '/dashboard/nominees': typeof DashboardNomineesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/vault': typeof DashboardVaultRoute
  '/dashboard/will': typeof DashboardWillRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/activity'
    | '/dashboard/contacts'
    | '/dashboard/legacy'
    | '/dashboard/lifeline'
    | '/dashboard/nominees'
    | '/dashboard/settings'
    | '/dashboard/vault'
    | '/dashboard/will'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/activity'
    | '/dashboard/contacts'
    | '/dashboard/legacy'
    | '/dashboard/lifeline'
    | '/dashboard/nominees'
    | '/dashboard/settings'
    | '/dashboard/vault'
    | '/dashboard/will'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/activity'
    | '/dashboard/contacts'
    | '/dashboard/legacy'
    | '/dashboard/lifeline'
    | '/dashboard/nominees'
    | '/dashboard/settings'
    | '/dashboard/vault'
    | '/dashboard/will'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/will': {
      id: '/dashboard/will'
      path: '/will'
      fullPath: '/dashboard/will'
      preLoaderRoute: typeof DashboardWillRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vault': {
      id: '/dashboard/vault'
      path: '/vault'
      fullPath: '/dashboard/vault'
      preLoaderRoute: typeof DashboardVaultRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/nominees': {
      id: '/dashboard/nominees'
      path: '/nominees'
      fullPath: '/dashboard/nominees'
      preLoaderRoute: typeof DashboardNomineesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/lifeline': {
      id: '/dashboard/lifeline'
      path: '/lifeline'
      fullPath: '/dashboard/lifeline'
      preLoaderRoute: typeof DashboardLifelineRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/legacy': {
      id: '/dashboard/legacy'
      path: '/legacy'
      fullPath: '/dashboard/legacy'
      preLoaderRoute: typeof DashboardLegacyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contacts': {
      id: '/dashboard/contacts'
      path: '/contacts'
      fullPath: '/dashboard/contacts'
      preLoaderRoute: typeof DashboardContactsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/activity': {
      id: '/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof DashboardActivityRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardActivityRoute: typeof DashboardActivityRoute
  DashboardContactsRoute: typeof DashboardContactsRoute
  DashboardLegacyRoute: typeof DashboardLegacyRoute
  DashboardLifelineRoute: typeof DashboardLifelineRoute
  DashboardNomineesRoute: typeof DashboardNomineesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardVaultRoute: typeof DashboardVaultRoute
  DashboardWillRoute: typeof DashboardWillRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivityRoute: DashboardActivityRoute,
  DashboardContactsRoute: DashboardContactsRoute,
  DashboardLegacyRoute: DashboardLegacyRoute,
  DashboardLifelineRoute: DashboardLifelineRoute,
  DashboardNomineesRoute: DashboardNomineesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardVaultRoute: DashboardVaultRoute,
  DashboardWillRoute: DashboardWillRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
